CPP_DIR = Cpp
C_DIR = C

CPP_OUTPUT = LRNE_cpp
C_OUTPUT = LRNE_c

all:                                                                                                                                                                                                        
	g++ ./$(CPP_DIR)/main.cpp -o $(CPP_OUTPUT)
	gcc ./$(C_DIR)/main.c -o $(C_OUTPUT)

clean:
	@rm $(CPP_OUTPUT)
	@rm $(C_OUTPUT)